#! /usr/bin/env bash
echo $PATH

#reinstall if modules are out of date!
npm ls || npm install
#run server

pkill -9 node
nohup node server.js >> ../level-twitter.log  2>> ../level-twitter.err.log &
//nohup proxy80 4567 &


